# -*- python -*-
import sys
Import("env")

env.Program("testFit", ["testFit.cc"], LIBS=env.getlibs("hscMosaic"))
env.Program("testWcs", ["testWcs.cc"], LIBS=env.getlibs("hscMosaic"))


#import lsst.tests
#tests = lsst.tests.Control(env, verbose = True)
#tests.run("*.cc")
