# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(['fluxfit',
                                  'matches',
                                  'mosaicfit/mosaicfit',
                                  'shimCameraGeom',
                                  'snapshot',
                                  'spatialCellSource'], addUnderscore=False)
